name: enviornment-demo
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip:
    - ipykernel~=6.0
    - azureml-core==1.47.0
    - azureml-dataset-runtime==1.47.0
    - azureml-defaults==1.47.0
    - azure-ml==0.0.1
    - azure-ml-component==0.9.15.post2
    - azureml-mlflow==1.47.0
    - azureml-contrib-services==1.47.0
    - torch-tb-profiler~=0.4.0
    - py-spy==0.3.12
    - debugpy~=1.6.3
    - azure-ai-ml==0.1.0b5
    - MarkupSafe==2.1.1
    - regex
