$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: none
image: mcr.microsoft.com/azureml/aifx/stable-ubuntu2004-cu116-py39-torch1121:latest
conda_file: conda.yml
description: Environment created from a Docker image plus Conda environment